### ISSUE TITLE
Configuration and run

### ISSUE THREAD

**Issue by rodrigojob** [clousale/amazon-sp-api-php#1]
Hello,
I tried use this API but don't have success.

I create the Configuration with access_token that I generate in Amazon SP-API.
But the erro is 
`403 Forbidden` response:
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "MissingAuthenticationTok (truncated...)

The username and password are necessary? This values are of sellercentral or cloudsale?

**Comment by clousale** [comment]
Hey @rodrigojob 
Please note that you don't communicate with clousale (we only provide this package, but has nothing to do with our services)

Could you please post the complete error message?
As from what i can see, it looks like you're not providing the authentication token (don't mistake this with the access token).
What is the exact code that you're using to call the API? (Please strip any live credentials)

**Comment by clousale** [comment]
Also, did you check the Developer Guide provided by Amazon?
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md

**Comment by rodrigojob** [comment]
Error message:

Exception when calling SalesApi->getOrderMetrics: [403] Client error: `GET https://sellingpartnerapi-na.amazon.com/sales/v1/orderMetrics?marketplaceIds=A2Q3Y263D00KWC&interval=2020-09-01T00%3A00%3A00-07%3A00--2020-10-04T00%3A00%3A00-07%3A00&granularity=DAY&buyerType=All&fulfillmentNetwork=AFN&firstDayOfWeek=Monday&sku=xxxx` resulted in a `403 Forbidden` response:
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "MissingAuthenticationTok (truncated...)

**Comment by clousale** [comment]
Hey @rodrigojob, i hope you don't mind that i improved a little your post formatting. 

As far as i can see your MWS Auth Token might be wrong, i have only seen the format `amzn.mws.*******************` so far.

I think we'll write a simple example next week for making an example call with auth.

**Comment by rodrigojob** [comment]
hallo @clousale, 
this format is better of future views.

- I don't longer remembered of MWS Auth Token, in lot part of my code I use DEVELOPER_ACCOUNT_NUMBER , but I found him and use it. But don't work.

- I used a same code of example for instanciate the client:     
```
$apiClient = new Swagger\Client\Api\AuthorizationApi(
    // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
    // This is optional, `GuzzleHttp\Client` will be used as default.
    new GuzzleHttp\Client()
);

```

- I'm using *-na.amazon, because I'm from Brazil.

**Comment by NishealJ** [comment]
Hi @clousale & @rodrigojob I too get this error, can you give more insights on how to solve?

**Comment by rodrigojob** [comment]
I don't solve.
I was unable to sign the request using Guzzle.

**Comment by zhanfjunjun** [comment]
Hello, can this SDK package generate the security token in the request header?

**Comment by cgaugel** [comment]
Any news?

**Comment by clousale** [comment]
Will be closed with PR #4 around tomorrow. Thanks to @rodrigojob

**Comment by clousale** [comment]
It's now merged. New release will be tagged today!

**Comment by TheViz02** [comment]
@clousale 
I've a issue regarding refresh token for login. Please share how to get refresh token for my application
