### ISSUE TITLE
Class 'ClouSale\AmazonSellingPartnerAPI\Api\EstimateTransportResponse' not found

### ISSUE THREAD

**Issue by lai3221** [clousale/amazon-sp-api-php#105]
When i use the api "estimateTransport"，it throw error   “Class 'ClouSale\AmazonSellingPartnerAPI\Api\EstimateTransportResponse' not found”

**Comment by gaurav-webs** [comment]
@lai3221 

add 
`use ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound\EstimateTransportResponse;` 
this after `namespace ClouSale\AmazonSellingPartnerAPI\Api;` 
in `vendor/clousale/amazon-sp-api-php/lib/Api/FbaInboundApi.php `  file.

and try again.

**Comment by lai3221** [comment]
> @lai3221
> 
> open `vendor/clousale/amazon-sp-api-php/lib/Api/FbaInboundApi.php ` file and
> add
> `use ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound\EstimateTransportResponse;`
> this after `namespace ClouSale\AmazonSellingPartnerAPI\Api;`
> 
> and try again.

Thanks
