### ISSUE TITLE
How can I decrypt report document?

### ISSUE THREAD

**Issue by mukul20** [clousale/amazon-sp-api-php#111]
Thanks for making this SKD available.
I'm unable to figure out how to decrypt report file returned by Amazon.
This is the format of response via Amazon:
array (
  'reportDocumentId' => '***',
  'url' => '***',
  'encryptionDetails' => 
  array (
    'standard' => 'AES',
    'initializationVector' => <24-digit-iv>,
    'key' => '***',
  ),
)

**Comment by mukul20** [comment]
Found it.
Link to the original issue: https://github.com/clousale/amazon-sp-api-php/issues/43

**Comment by Cord4MdDeveloper** [comment]
$key = base64_decode('xxxxx');
$iv = base64_decode('xxxxxx');
$decryptedData = openssl_decrypt(file_get_contents($url), 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);
 
if($compression_algorithm && $compression_algorithm == 'GZIP'){
    $decryptedData = gzdecode($decryptedData);
}

**Comment by mukulcap** [comment]
@Cord4MdDeveloper thanks a lot.
