### ISSUE TITLE
Not getting quantity from getShipmentItemsByShipmentId and getShipmentItems API

### ISSUE THREAD

**Issue by gaurav-webs** [clousale/amazon-sp-api-php#112]
@clousale 

I am not getting `quantity_shipped` , `quantity_received` , `quantity_in_case` from  [getShipmentItemsByShipmentId](https://github.com/clousale/amazon-sp-api-php/blob/master/docs/Api/FbaInboundApi.md#getshipmentitemsbyshipmentid) and [getShipmentItems](https://github.com/clousale/amazon-sp-api-php/blob/master/docs/Api/FbaInboundApi.md#getshipmentitems) API

Here is my response of SP API 
![screenshot-localhost-2021 06 30-18_07_36 (1)](https://user-images.githubusercontent.com/78719205/123962994-ad119380-d9cf-11eb-88c5-c00e6d90be3f.jpg)

But I am getting proper `quantity_shipped`,  `quantity_received`, and `quantity_in_case` from MWS API

Here is my MWS API response

![screenshot-localhost-2021 06 30-18_19_41](https://user-images.githubusercontent.com/78719205/123963389-08438600-d9d0-11eb-9829-59f40c6be8f1.jpg)

Please can any one help,
thanks.

**Comment by pengjun132** [comment]
I have the same questions with you . Do you have a good solution now ?

**Comment by gaurav-webs** [comment]
Update `vendor/clousale/amazon-sp-api-php/lib/Models/FulfillmentInbound/InboundShipmentItem.php` file and replace `protected static $swaggerTypes`

currently, in file, you can see this below code

protected static $swaggerTypes = [
        'shipment_id' => 'string',
'seller_sku' => 'string',
'fulfillment_network_sku' => 'string',
'quantity_shipped' => '\ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound\Quantity',
'quantity_received' => '\ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound\Quantity',
'quantity_in_case' => '\ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound\Quantity',
'release_date' => '\ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound\DateStringType',
'prep_details_list' => '\ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound\PrepDetailsList',    ];

--------------------------------------------------Replace With--------------------------------------------------------

protected static $swaggerTypes = [
        'shipment_id' => 'string',
'seller_sku' => 'string',
'fulfillment_network_sku' => 'string',
'quantity_shipped' => 'int',
'quantity_received' => 'int',
'quantity_in_case' => 'int',
'release_date' => '\ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound\DateStringType',
'prep_details_list' => '\ClouSale\AmazonSellingPartnerAPI\Models\FulfillmentInbound\PrepDetailsList',    ];

update this change and you will get the response.

Hope this is helpful.
