### ISSUE TITLE
Getting InvalidInput from sandbox 

### ISSUE THREAD

**Issue by gaurav-webs** [clousale/amazon-sp-api-php#114]
Every time when I call [updateInboundShipment](https://github.com/clousale/amazon-sp-api-php/blob/master/docs/Api/FbaInboundApi.md#updateinboundshipment) API to cancel the shipment i am always getting this response

```
{
 "errors": [
	{
	"message": "Invalid request body: [instance type (object) does not match any allowed primitive type (allowed: ["array"])]",
	"code": "InvalidInput"
	}
  ]
}
```

Here following is my request data of [\Swagger\Client\Models\InboundShipmentRequest](https://github.com/clousale/amazon-sp-api-php/blob/master/docs/Model/InboundShipmentRequest.md)

Here my Request data

![screenshot-jsonformatter org-2021 07 02-19_18_11](https://user-images.githubusercontent.com/78719205/124285245-6062bf80-db6b-11eb-863b-216ab6917745.jpg)

can anyone explain why I am getting this error, please?

Thanks.

**Comment by gokigoks** [comment]
Hey there,

How did you manage to direct your requests to Amazon's sandbox? Any help would be greatly appreciated as I can't find anything on how to manage this.

**Comment by gaurav-webs** [comment]
@gokigoks 

Everything is just the same as normal API calls.

You just need to change `endpoint` to the `https://sandbox.sellingpartnerapi-na.amazon.com`.

**Note:- I am using `us-east-1` NORTH_AMERICA Region that's why I used  `https://sandbox.sellingpartnerapi-na.amazon.com` for other regions you need to update sandbox URL.** 

Here is my sample option array

`$options = [
                'refresh_token' => XXXX,
                'client_id' => XXXX,
                'client_secret' => XXXX,
                'region' => 'us-east-1',
                'access_key' => XXXXX,
                'secret_key' => XXXXX,
               'endpoint' => 'https://sandbox.sellingpartnerapi-na.amazon.com',
                'role_arn' => XXXXX,
            ];`

Hope this is useful.

**Comment by gokigoks** [comment]
@gaurav-webs  Thank you for the help. I keep getting InternalFailure 500 in my requests though. I'm using this model document as a reference [link](https://github.com/amzn/selling-partner-api-models/blob/main/models/reports-api-model/reports_2020-09-04.json). 

I was wondering if this is due to the sandbox using camelcase in the parameter names while the library uses snakecase, because if I remove 1 of the parameters, it shows a message `Invalid request body: [object has missing required properties ([\"marketplaceIds\"])]`. This is the report body I'm building.

`$body = new ClouSale\AmazonSellingPartnerAPI\Models\Reports\CreateReportSpecification(
    [
        'report_type' => 'GET_MERCHANT_LISTINGS_ALL_DATA',
        'marketplace_ids' => ['ATVPDKIKX0DER', 'A1PA6795UKMFR9'], 
        'data_start_time' => '2019-12-10T20:11:24.000Z',
    ]
);`

sorry for the bother. Just in desperate need of any help understanding the sandbox.

**Comment by gaurav-webs** [comment]
@gokigoks 
Here is my CreateReportSpecification for sandbox call 

$marketPlaceIdArray = array("A1PA6795UKMFR9","ATVPDKIKX0DER");
$reportType = 'GET_MERCHANT_LISTINGS_ALL_DATA';
$createReportSpecification = new CreateReportSpecification();
$createReportSpecification['report_type'] = $reportType;
$createReportSpecification['data_start_time'] = "2019-12-10T20:11:24.000Z";
$createReportSpecification['marketplace_ids'] = $marketPlaceIdArray;
$requestReportInfo = $apiInstance->createReport($createReportSpecification);

Also as I have reviewed the package code and it has something like this that it will convert your `report_type` parameter to `reportType`, `data_start_time` to `dataStartTime` and `marketplace_ids` to `marketplaceIds` automatically when it calls amazon. so you just need to pass the parameter as per the package document.

_one trick you can try:- If you want to check that your parameter is set properly or not, you can convert your `$createReportSpecification` object to the string and just print it and you will get the same parameter as the amazon document in camelcase, and if it didn't convert your snakecase to the camelcase then there is something issue while creating your request body._

_As you can see in above my code I have set everything in snakecase and when I print my `$createReportSpecification` object like this `echo((string)$createReportSpecification);die;` it will display something like this_
![screenshot-localhost-2021 07 23-11_57_49](https://user-images.githubusercontent.com/78719205/126744927-ec59d45f-0d86-4dc8-a13d-165a7c3d33d2.jpg)

Hope this is helpful.
