### ISSUE TITLE
createInboundShipmentPlanRequest is error

### ISSUE THREAD

**Issue by pengjun132** [clousale/amazon-sp-api-php#124]
![image](https://user-images.githubusercontent.com/12582026/126425378-4a002ca3-dd3c-4491-825b-d17c96475e0a.png)

$resourcePath = '/fba/inbound/v0/plans';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

return $this->generateRequest($multipart, $formParams, $queryParams, $resourcePath, $headerParams, 'POST', $httpBody);

empty params for request

**Comment by gaurav2262** [comment]
@pengjun132 

You need to update `$httpBody = '';` to `$httpBody = $body;`, and its working fine.

Hope this is useful.

**Comment by pengjun132** [comment]
> @pengjun132
> 
> You need to update `$httpBody = '';` to `$httpBody = $body;`, and its working fine.
> 
> Hope this is useful.

thanks . it works
