### ISSUE TITLE
cannot update Inventory(createFeed returns success, but update is not completed)

### ISSUE THREAD

**Issue by kougensyou** [clousale/amazon-sp-api-php#130]
I ran following codes, trying to update the quantity of inventories.

        $feed_params = [
            'feed_type' => 'POST_INVENTORY_AVAILABILITY_DATA',
            'marketplace_ids' => ['MY_MARKETPLACE_IDS'],
            'input_feed_document_id' => $result->getPayload()->getFeedDocumentId(),
            'feed_options' => '<?xml version="1.0" encoding="utf-8" ?>
            <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn- envelope.xsd">
            <Header>
            <DocumentVersion>1.01</DocumentVersion> <MerchantIdentifier>'.$accessToken.'</MerchantIdentifier> </Header>
            <MessageType>Inventory</MessageType>
            <Message>
            <MessageID>1</MessageID> <OperationType>Update</OperationType>
            <Inventory>
            <SKU>SKUNUMBER</SKU>
            <Quantity>60</Quantity> <FulfillmentLatency>1</FulfillmentLatency> </Inventory>
            </Message>
            </AmazonEnvelope>'
        ];
        
        $body2 = new \ClouSale\AmazonSellingPartnerAPI\Models\Feeds\CreateFeedSpecification($feed_params); // \Swagger\Client\Models\CreateFeedSpecification | 
        $result2 = $apiInstance->createFeed($body2);

It returns success response, however, when I check the quantity of inventory in the sellercentral, the quantity was not updated.

is something missing in xml parameters?

Thanks.

**Comment by gaurav-webs** [comment]
@kougensyou 

when you submit your feed, your feed first goes to IN_QUEUE status, and then it moves to IN_PROGRESS and it will take few minutes to DONE, once your feed is in DONE status your feed is executed successfully.

**Comment by kougensyou** [comment]
@gaurav-webs 

Thank you for your comment. I checked the feed status, but all of them were DONE and still the quantity was not updated.
Is there the possibility that something is missing in the feed_option?

**Comment by gaurav-webs** [comment]
@kougensyou 

have you checked calling `getFeedDocument`  API? if your feed status is DONE but if there is something wrong in your feed that you can check in  `getFeedDocument`, if there is something wrong in your feed you can see the error or warning in `getFeedDocument`,

in the `getFeedDocument` response you can get a URL  using that URL you can get the document and check your feed is valid or not.

**Comment by kougensyou** [comment]
@gaurav-webs 
I executed getFeedDocument, and following error showed up.

>"XML Parsing Fatal Error at Line 17, Column 26: Content is not allowed in trailing section. Content is not allowed in trailing section."
※Line 17 indicates the end of xml file</AmazonEnvelop>

I followed the document below and created xml.
https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf

Is something missing in the xml?

<?xml version="1.0" encoding="utf-8" ?>
        <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amznenvelope.xsd">
        <Header>
        <DocumentVersion>1.01</DocumentVersion>
        <MerchantIdentifier>MY_MERCHANT_IDENTIFIER</MerchantIdentifier>
        </Header>
        <MessageType>Inventory</MessageType>
        <Message>
        <MessageID>1</MessageID>
        <OperationType>Update</OperationType>
        <Inventory>
        <SKU>MY_SKU</SKU>
        <Quantity>60</Quantity>
        <FulfillmentLatency>1</FulfillmentLatency>
        </Inventory>
        </Message>
        </AmazonEnvelope>

**Comment by kougensyou** [comment]
@gaurav-webs 
Adding the <?xml version="1.0" encoding="UTF-8"?> solved this.
Now, there are no errors when calling the getFeedDocument.Thanks!

But, when I looked seller central, still quantity was not updated.
is there any time lag until the quantity on the seller central is reflected onto what I updated?

**Comment by gaurav-webs** [comment]
ok, that's great,

sorry, but I don't know about that, that you have to find.

**Comment by kougensyou** [comment]
@gaurav-webs 
OK, Thank you for your continuous advice！

**Comment by jsanthoshaws** [comment]
HI Team,

[kougensyou](https://github.com/kougensyou)  is this issue resolved ? can you please share the codes sample ? Thanks!
