### ISSUE TITLE
cannot update inventory quantity(createFeed returns success, but not updated)

### ISSUE THREAD

**Issue by kougensyou** [clousale/amazon-sp-api-php#132]
I ran following codes, trying to update the quantity of inventories.

        $feed_params = [
            'feed_type' => 'POST_INVENTORY_AVAILABILITY_DATA',
            'marketplace_ids' => ['MY_MARKETPLACE_IDS'],
            'input_feed_document_id' => $result->getPayload()->getFeedDocumentId(),
            'feed_options' => '<?xml version="1.0" encoding="utf-8" ?>
            <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn- envelope.xsd">
            <Header>
            <DocumentVersion>1.01</DocumentVersion> <MerchantIdentifier>MERCHANT_ID</MerchantIdentifier> </Header>
            <MessageType>Inventory</MessageType>
            <Message>
            <MessageID>1</MessageID> <OperationType>Update</OperationType>
            <Inventory>
            <SKU>SKUNUMBER</SKU>
            <Quantity>60</Quantity> <FulfillmentLatency>1</FulfillmentLatency> </Inventory>
            </Message>
            </AmazonEnvelope>'
        ];
        
        $body2 = new \ClouSale\AmazonSellingPartnerAPI\Models\Feeds\CreateFeedSpecification($feed_params); // \Swagger\Client\Models\CreateFeedSpecification | 
        $result2 = $apiInstance->createFeed($body2);

It returns success response, however, when I check the quantity of inventory in the sellercentral, the quantity was not updated.

I also download and decrypt the feed processing report and returned no errors , which means the feed submission was complete.

Any ideas what caused this problem?

Thanks.

**Comment by t-poeschl** [comment]
Same Problem, did you find the exception?

**Comment by kougensyou** [comment]
Not yet, I'm in the middle of asking for help to Amazon Help Center.
(The problem seems coming from Amazon SP API, not this library.)

**Comment by kougensyou** [comment]
Since this problem has nothing to do with this library, I close this issue

**Comment by vikingcodes** [comment]
@kougensyou FYI: MWS takes approx 15 minutes to update inventory on seller central.
