### ISSUE TITLE
Messaging->confirmCustomizationDetails return Invalid amazonOrderId and template combination

### ISSUE THREAD

**Issue by fengmiq** [clousale/amazon-sp-api-php#14]
POST /messaging/v1/orders/111-7414665-8741XXX/messages/confirmCustomizationDetails
return 403 Forbidden,message:Invalid amazonOrderId and template combination
I'm broken,can you help me

**Comment by clousale** [comment]
Hi @fengmiq could you please provide sample code?

**Comment by fengmiq** [comment]
```
<?php
$apiInstance = new MessagingApi();
$amazon_order_id = "111-7414665-8741XXX";
$marketplace_ids = array("ATVPDKIKX0DER");
$data = [
	'text' => "This is test message"
];
$body = new CreateConfirmCustomizationDetailsRequest($data);
try {
	$result = $apiInstance->confirmCustomizationDetails($amazon_order_id, $marketplace_ids, $body);
	dump($result);
} catch (Exception $e) {
	echo 'Exception when calling MessagingApi->confirmCustomizationDetails: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by clousale** [comment]
Hey @fengmiq thanks for the sample.
As i can see, there is neither `CreateConfirmCustomizationDetailsRequest` nor `MessagingApi` request in this repository. Are you by any chance using another lib?!

**Comment by fengmiq** [comment]
this sdk not contians message api and uploads api

**Comment by clousale** [comment]
Hi @fengmiq could you please upgrade to `2.0` and check again please? 
Please adapt the sample code from the README.

**Comment by clousale** [comment]
In 2.1 we will be adding Messaging API and the Uploads API as they are the "freshest" APIs of the new Selling Partner API

**Comment by kingsun-he** [comment]
> In 2.1 we will be adding Messaging API and the Uploads API as they are the "freshest" APIs of the new Selling Partner API

Hi clousale, 
Do you try to use the shipping-API? I get a 500 error "We encountered an internal error. Please try again". I have upgrade to 2.0 version.

Here is my code.
`$apiInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\ShippingApi(
    new GuzzleHttp\Client(),
    $config
);

$shipping_id = "TEST_CASE_200"; // string | An Amazon-defined order identifier, in 3-7-7 format.

try {
    $result = $apiInstance->getShipment($shipping_id);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling ShippingApi->getShipment: ', $e->getMessage(), PHP_EOL;
}`

When I try to call $result = $apiInstance->getAccount()， It can be called successfully, thought it return nothing(It should return a account_id "2755049166" )

**Comment by kingsun-he** [comment]
When I tried to use SolicitationsApi, It returns 403 error "Access to requested resource is denied."
Here is my code : 
`
$apiInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\SolicitationsApi($config);

try {
    //$result = $apiInstance->getSolicitationActionsForOrder('123-1234567-1234567', ['ATVPDKIKX0DER']);
    $result = $apiInstance->createProductReviewAndSellerFeedbackSolicitation('123-1234567-1234567', ['ATVPDKIKX0DER']);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling ShippingApi->getShipment: ', $e->getMessage(), PHP_EOL;
}
`

It is so strange.

**Comment by clousale** [comment]
@kingsun-he this seems like a different issue. can you open a new issue, post the example code and the `$config->setDebug(true);` and post the output?

**Comment by kingsun-he** [comment]
> @kingsun-he this seems like a different issue. can you open a new issue, post the example code and the `$config->setDebug(true);` and post the output?

OK. Open an new issue. Thanks in advance.
