### ISSUE TITLE
Swagger\Client\Configuration' not found in ...

### ISSUE THREAD

**Issue by SARANGHAJA** [clousale/amazon-sp-api-php#148]
The following error occurred in the following code while using 'getOrders' sample code

[code]
`require_once(__DIR__ . '/vendor/autoload.php');`
`$config = Swagger\Client\Configuration::getDefaultConfiguration();`

[error]
`Fatal error: Uncaught Error: Class 'Swagger\Client\Configuration' not found in ...`

The 'vendor/autoload.php' include was fine.
because, I succeeded in receiving accessToken using the code below.
`$accessToken = \ClouSale\AmazonSellingPartnerAPI\SellingPartnerOAuth::getAccessTokenFromRefreshToken(
    $options['refresh_token'],
    $options['client_id'],
    $options['client_secret']
);`

I don't know what the problem.
Help me

**Comment by maydo** [comment]
i have same issue, did you find any solution ?

**Comment by TheViz02** [comment]
Namespace has been changed. It's no swagger, it's `ClouSale\AmazonSellingPartnerAPI\Api`
