### ISSUE TITLE
Amazon AWS SDK provides code for signing PSR7 requests

### ISSUE THREAD

**Issue by piotr-lottestyle** [clousale/amazon-sp-api-php#21]
Please consider this piece of code

```php
   function signRequest(Request $request)
    {
        $signatureV4 = new \Aws\Signature\SignatureV4(
            'execute-api',
            $this->config->getApiKey('region')
        );

        $stsClient = new \Aws\Sts\StsClient([
            'region' => $this->config->getApiKey('region'),
            'version' => '2011-06-15',
            'credentials' => new Credentials(
                $this->config->getApiKey('access_key'),
                $this->config->getApiKey('secret_key')
            ),
        ]);

        $stsResult = $stsClient->assumeRole([
            'RoleArn' => $this->config->getApiKey('role_arn'),
            'RoleSessionName' => 'amazon-sp-api-php',
            'region' => $this->config->getApiKey('region'),
        ]);

        $credentials = $stsClient->createCredentials($stsResult);

        $request = $request->withHeader(
            'x-amz-access-token',
            $this->config->getAccessToken()
        );

        return $signatureV4->signRequest(
            $request,
            $credentials
        );
    }
```

Documentation: https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Signature.SignatureV4.html

**Comment by piotr-lottestyle** [comment]
with such code it is also possible to simply extend Guzzle Client like so

```php
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use Psr\Http\Message\RequestInterface;

class SellingPartnerApiClient extends Client implements ClientInterface
{
    use SignsRequests;

    public function sendAsync(RequestInterface $request, array $options = [])
    {
        $signedRequest = $this->signRequest($request);

        return parent::sendAsync($signedRequest, $options);
    }

    public function send(RequestInterface $request, array $options = [])
    {
        $signedRequest = $this->signRequest($request);

        return parent::send($signedRequest, $options);
    }
}
```

**Comment by clousale** [comment]
Hi @piotr-lottestyle thank you for your interest in this package.

For your code, you'd need the AWS SDK for PHP, but we just removed that by rebuilding the STS AssumeRole Call in 2.1.

Is there anything wrong with the current implementation?

**Comment by piotr-lottestyle** [comment]
you edit code that was supposed to be generated only automatically

**Comment by clousale** [comment]
@piotr-lottestyle that is right. The `swagger-codegen` output however is just the base of this and was a one-time only bootstrap operation.
Therefore we changed a lot of things including your suggestions, refactoring of the code, signature of the requests, etc.

**Comment by piotr-lottestyle** [comment]
you'll have nightmare if new version of models is released. I saw you already had to implement changes to signing code (b1cb0fa2) and you write OAuth code by yourself.  Lot of code is straight out broken (for example FeedList::listInvalidProperties) while it's working straight out of the box if you use OpenAPI instead swagger.

Good luck.
