### ISSUE TITLE
Use OpenAPI generator instead swagger-codegen-cli

### ISSUE THREAD

**Issue by piotr-lottestyle** [clousale/amazon-sp-api-php#23]
We are trying to integrate SP-API into our projects and I had great struggle with all versions of swagger (which is recommended by Amazon docs)

I decided to try out OpenAPI generator and it is superior to swagger-codegen-cli

Example:

```php
java -jar ./openapi-generator-cli-4.3.1.jar generate \
	-i selling-partner-api-models/models/catalog-items-api-model/catalogItemsV0.json \
	-g php \
	-o out \
	--model-package='Catalog' \
	--invoker-package 'App\Services\Amazon\SellingPartnerApi'
```

All code runs out of the box, there is no problem with `parent::listInvalidProperties()` and other stuff, go give it a try

**Comment by clousale** [comment]
Hi @piotr-lottestyle thanks for your interest in this package.
Please upgrade to the newest version.

If you have any specific issues with it, please let me know. Feel free to open a new ticket with sample code & debug output (`$config->setDebug(true)`).
