### ISSUE TITLE
Help - Class 'Swagger\Client\Api\FeesApi' not found

### ISSUE THREAD

**Issue by nikgilbe** [clousale/amazon-sp-api-php#35]
Hi. I'm a relative newbie to PHP, and have no experience with Swagger. I've searched everywhere, but am stuck. 

I've managed to get all the refresh tokens, IAM roles etc. setup, and can successfully connect and see data returned. However, when I try and use the examples here (e.g. $apiInstance = new Swagger\Client\Api\FeesApi...) I get the above error, and I just have no idea what I need to be doing, or what I'm doing wrong. 

If anyone is able to point me in the right direction, I'd be eternally grateful.

Thanks

**Comment by arturll7** [comment]
Hi @nikgilbe 
You should you like the following,

**`$apiInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\FeesApi($config);`**

**Comment by nikgilbe** [comment]
Thank you - much appreciated - I thought I'd tried something similar, but I've managed to get it all working now (other than for some reason Amazon don't like GBP currency code, and some of the fees being returned are way different to what Seller Central website is showing)
