### ISSUE TITLE
how to open report document file which is binary?

### ISSUE THREAD

**Issue by arturll7** [clousale/amazon-sp-api-php#43]
Hello,

I am using the ReportsApi::**getReportDocument** method to get report document details. I download the report with using URL parameter. The downloaded report file is **binary**.

For the next step, I know, I need to **decrypt** and **uncompress** (GZIP) the file. Because the file is binary, I cannot do these operations with **PHP**.

Can someone help me on this please?

Thanks.

**Comment by sirajea** [comment]
Let's say `$report` holds the report reponse payload. You can do:
```
$key = base64_decode($report->getEncryptionDetails()->getKey());
$iv = base64_decode($report->getEncryptionDetails()->getInitializationVector());
$data = openssl_decrypt(file_get_contents($report->getUrl()), 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);
```
`$data` now holds the decrypted report data.

**Comment by arturll7** [comment]
Hi @sirajea,

Thank you for the answer.

I tried your solution. When I print **$data**, it contains �����۴��\\�� characters. Like I said in my first comment, report file content is **binary** before decryption. After decryption, the content is again binary. Because of that, I cannot parse report document content.

Have you manage to access the report document content before? Could you please say the whole **decryption** and **uncompression** process with **PHP**?

**Comment by arturll7** [comment]
SOLVED.

After decryption, I did gzip decompression operation on content with PHP. Finally, I reached the file content as a string.

**Comment by shirushi-dev** [comment]
@arturll7

It's the same situation. Could you show me the code?

**Comment by Nireshgit** [comment]
> **SOLVED**.
> 
> After decryption, I did **gzip decompression** operation on content with PHP. Finally, I reached the file content as a **string**.

Can you please share the code if possible?

**Comment by Nireshgit** [comment]
> decompression

Hi did you find the solution?

**Comment by Nireshgit** [comment]
> @arturll7
> 
> It's the same situation. Could you show me the code?

@sirajea did you find the solution?

**Comment by Balinvest** [comment]
```
@Nireshgit 

$apiInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\ReportsApi($config);
$report_document_id = "amzn1.spdoc.1.3.yyy.zzz.1118";

$result = $apiInstance->getReportDocument($report_document_id);

$key = base64_decode($result->getPayload()->getEncryptionDetails()->getKey());
$iv = base64_decode($result->getPayload()->getEncryptionDetails()->getInitializationVector());
$data = openssl_decrypt(file_get_contents($result->getPayload()->getUrl()), 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);

echo "<pre>";
print_r($data);
echo "</pre>";
```

**Comment by deadmouse** [comment]
@Nireshgit 

```
$apiInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\ReportsApi($config);
$report_document_id = "amzn1.spdoc.1.3.yyy.zzz.1118";

$result = $apiInstance->getReportDocument($report_document_id);

$key = base64_decode($result->getPayload()->getEncryptionDetails()->getKey());
$iv = base64_decode($result->getPayload()->getEncryptionDetails()->getInitializationVector());
$data = openssl_decrypt(file_get_contents($result->getPayload()->getUrl()), 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);

echo "<pre>";
print_r($data);
echo "</pre>";
```
