### ISSUE TITLE
GET_REFERRAL_FEE_PREVIEW_REPORT

### ISSUE THREAD

**Issue by webinsect-rishabh** [clousale/amazon-sp-api-php#44]
I want to get REFERRAL_FEE_PREVIEW_REPORT but it always leave me with 403 error .
error details:-
"code": "Unauthorized",
"message": "Access to the resource is forbidden"

Earlier i tried to get GET_FLAT_FILE_OPEN_LISTINGS_DATA and GET_MERCHANT_LISTINGS_DATA reports and that worked for me. But REFERRAL_FEE_PREVIEW_REPORT is not working for me.

Is there anyone with same issue or some one could help me to get rid of this.
Thanks in advance

**Comment by webinsect-rishabh** [comment]
@clousale can you please help on this?

**Comment by mikconstantinou** [comment]
@webinsect-rishabh I'm currently experiencing the exact same issue. How did you resolve this in the end?

**Comment by webinsect-rishabh** [comment]
have you given all the permissions to your app in amazon seller central ?  and also check the developer permission also 
![image](https://user-images.githubusercontent.com/79914693/155492508-f1ff929f-c901-48f1-adf0-dc8cb2127eab.png)
