### ISSUE TITLE
Method to get all categories in a marketplace?

### ISSUE THREAD

**Issue by arturll7** [clousale/amazon-sp-api-php#45]
Hello,

Does anyone know the method to get all categories in a marketplace with marketplace_id?

Thanks

**Comment by ouroboros25** [comment]
@arturll7 Did you find an answer?

**Comment by arturll7** [comment]
**SOLVED**. @ouroboros25 

You should use the **Browse-Tree Report**:
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#browse-tree-report

**Comment by ouroboros25** [comment]
@arturll7  Sorry, but can you give an example of the correct code to get all categories in a marketplace?

**Comment by arturll7** [comment]
@ouroboros25 I have not implement the code yet. If you do, you can also put it here.
