### ISSUE TITLE
getInventorySummaries

### ISSUE THREAD

**Issue by Chiuchiuchiu** [clousale/amazon-sp-api-php#50]
Hello, What granularity do "granularity type" and "granularity ID" refer to?
https://github.com/clousale/amazon-sp-api-php/blob/master/docs/Api/FbaInventoryApi.md

**Comment by limjim** [comment]
See details here: 
https://github.com/amzn/selling-partner-api-models/blob/main/models/fba-inventory-api-model/fbaInventory.json

**Comment by Chiuchiuchiu** [comment]
> Granularity description: "Describes a granularity at which inventory data can be aggregated. For example, if you use Marketplace granularity, the fulfillable quantity will reflect inventory that could be fulfilled in the given marketplace".
> 
> See details here:
> https://github.com/amzn/selling-partner-api-models/blob/main/models/fba-inventory-api-model/fbaInventory.json
> 
> Hope to help you!

Yeah, I had found the answer from your url on line 26. Thanks!
