### ISSUE TITLE
The security token included in the request is invalid

### ISSUE THREAD

**Issue by alpapazzo** [clousale/amazon-sp-api-php#52]
Hello, using the clousale project and calling the function getCatalogItemRequest I got the error about the scope of the region, then I edited the region code to "us-east-1" and I solved that, but now I had this error: 

"message": "The security token included in the request is invalid.", "code": "InvalidInput"

What is the 'security token' ? Reading the SP-Api guide I know I just need the refresh token and the access token. I have both. But what about the security token. And why it says it is invalid ? 

Anyone knows why I got this error ?

Thanks

**Comment by sunil11475-dev** [comment]
It must be refersh token, Without looking code i suggest but to call getCatalogItemRequest, you need - 
```
$config->setAccessToken('Atza|IwEBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'); //access token of Selling Partner / Refresh token
$config->setApiKey("accessKey", 'AKIA2xxxxxxxxxxxxx'); // Access Key of IAM
$config->setApiKey("secretKey", '94U4Gi81Tpxxxxxxxxxxxxxxx'); // Secret Key of IAM
$config->setApiKey("region", 'us-east-1'); //region of MarketPlace country
```
and refresh token expiers after `3600` so you have to get new token to make call.

**Comment by alpapazzo** [comment]
Thank you for you reply I m reinstalling it.
