### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by alpapazzo** [clousale/amazon-sp-api-php#55]
Hello, I m new with Composer. I installed the Clousale project by composer. 
Now I have this structure in local:

www(root) 
  -vendor
  -clousale
         ----amazon-sp-api-php-master
                    ------docs
                    ------lib
  -composer
  -guzzlehttp
  -ect...

Just under 'www' I have my test file, with just this rows:

```
require_once(__DIR__ . '/vendor/autoload.php');
$config = ClouSale\Client\Configuration::getDefaultConfiguration();
```

It give me this error: 
Uncaught Error: Class 'ClouSale\Client\Configuration' not found

Is the structure correct ? is it installed correctly ? Any help please ?

**Comment by sunil11475-dev** [comment]
Use this - \ClouSale\AmazonSellingPartnerAPI for path

require_once( '/vendor/autoload.php');
$config = ClouSale\AmazonSellingPartnerAPI \Configuration::getDefaultConfiguration();

**Comment by alpapazzo** [comment]
Thank you for you reply, but I got the same error
Fatal error: Uncaught Error: Class 'ClouSale\AmazonSellingPartnerAPI\Configuration' not found

**Comment by sunil11475-dev** [comment]
I have checked and its working perfectly. Can you paste full error so i can check
Please take the forward slash from - `require_once( 'vendor/autoload.php');` and check

$config = \ClouSale\AmazonSellingPartnerAPI\Configuration::getDefaultConfiguration();

**Comment by alpapazzo** [comment]
Give the same error: 
Fatal error: Uncaught Error: Class 'ClouSale\AmazonSellingPartnerAPI\Configuration' not found in C:\Program Files\EasyPHP-Devserver-17\eds-www\test.php:7 Stack trace: #0 {main} thrown in C:\Program Files\EasyPHP-Devserver-17\eds-www\test.php on line 7

It can't find the class file, I think the path, or structure of directories is not correct. But have you the same structure ?
Like this:
www(root)
-vendor
-clousale
----amazon-sp-api-php-master
------docs
------lib
-composer
-guzzlehttp
-ect...

I think this structure is wrong....

**Comment by alpapazzo** [comment]
Yes I installed it by composer, but I seen some differences between the code in the composer version and the code downloaded by github. Now I try to use the code downloaded by github, some files are different..

**Comment by sunil11475-dev** [comment]
In structure which you have provided it shows **www** and in error the calling file shows in **eds-www**\test.php

if your test.php file and vendor folder in same www folder then` require_once( 'vendor/autoload.php');` will work.

**Comment by dopeeh** [comment]
> I solved: in the composer/autoload_static.php there are 2 variables
> 
> public static $prefixLengthsPsr4
> public static $prefixDirsPsr4
> 
> pointing to Swagger folders, I changed them with the correct name of the folders and now it import the class correctly.
> 
> Thank you for you reply ;)

What did it need to be instead of the Swagger folders? The same swagger folders in a different path or? I'm running in to the same problem..

**Comment by maydo** [comment]
> What did it need to be instead of the Swagger folders? The same swagger folders in a different path or? I'm running in to the same problem..

any solution for this ? same issue
