### ISSUE TITLE
\ClouSale\AmazonSellingPartnerAPI\AssumeRole::assume cannot work with MissingAuthenticationToken error message

### ISSUE THREAD

**Issue by lily-PHP** [clousale/amazon-sp-api-php#63]
Hello, 
here is my request code:
$options = [
    'refresh_token' => '', // Aztr|...
    'client_id' => 'amzn1.application-oa2-client.01220xxxx', // App ID from Seller Central, amzn1.sellerapps.app.cfbfac4a-......
    'client_secret' => 'c1bd17bbcf87638d7c281xx', // The corresponding Client Secret
    'region' => \ClouSale\AmazonSellingPartnerAPI\SellingPartnerRegion::$EUROPE, // or NORTH_AMERICA / FAR_EAST
    'access_key' => 'AKIA23PQxxxxxx', // Access Key of AWS IAM User, for example AKIAABCDJKEHFJDS
    'secret_key' => 'YiZFcukZPxxxxxxx', // Secret Key of AWS IAM User
    'endpoint' => \ClouSale\AmazonSellingPartnerAPI\SellingPartnerEndpoint::$EUROPE, // or NORTH_AMERICA / FAR_EAST
    'role_arn' => 'arn:aws:iam::xxx', // AWS IAM Role ARN for example: arn:aws:iam::123456789:role/Your-Role-Name
];
$assumedRole = \ClouSale\AmazonSellingPartnerAPI\AssumeRole::assume(
    $options['region'],
    $options['access_key'],
    $options['secret_key'],
    $options['role_arn']
);

I stuck here several days and can't get the AWS tempory security credentials. 
I am sure I had setup my IAM user or role with correct sts policy correctly, but I still only can get error message......
here the AWS STS server always return this error message:
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
	<Error>
		<Type>Sender</Type>
		<Code>MissingAuthenticationToken</Code>
		<Message>Request is missing Authentication Token</Message>
	</Error>
	<RequestId>46b788f7-7d9a-49d0-8d92-9a981b3b4a59</RequestId>
</ErrorResponse>

Can anyone help? I already stuck here several days.  :( 
Looking forward to get some reply. 
Thank you very much,
Lily

**Comment by lily-PHP** [comment]
sorry for bothering. I sent the wrong header format before. now it is no problem here.  :)

**Comment by gokigoks** [comment]
@lily-PHP Hi, sorry for bothering. We have the same issue however I have not solved mine yet. Can you please let me know which header you were sending wrong? also if you can post the snipper of your assume role section, I'd greatly appreciate it.. thank you.

**Comment by TheViz02** [comment]
@lily-PHP @gokigoks 
Hello,
I've a issue regarding refresh token in amazon SP-API. What steps I need to do to get token?? Please share it with me ASAP!!!
It's urgent.
