### ISSUE TITLE
How to get historical order details?

### ISSUE THREAD

**Issue by arturll7** [clousale/amazon-sp-api-php#66]
Hello,

I want to get the past **orders**. Do I need to use **orders api** or **reports api** (GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL or another report type) for this?

Could you help me for this?

Thanks

**Comment by alfredone270895** [comment]
Orders api but is not working ..  i receiving this error 
<br />
<b>Fatal error</b>:  Cannot use "parent" when current class scope has no parent in <b>/home/boxped/api.boxped.com/vendor/clousale/amazon-sp-api-php/lib/Models/Orders/OrderList.php</b> on line <b>170</b><br />

I found solution removing the OrdersApi core from Clousale api moving request to internal folder and returning the amazon object .

**Comment by arturll7** [comment]
Hi @alfredone270895, Thank you for your answer.
I am getting orders successfully with Clousale/OrdersApi/getOrders method.
