### ISSUE TITLE
TokenApi

### ISSUE THREAD

**Issue by alpapazzo** [clousale/amazon-sp-api-php#76]
Hello,
about the TokenApi, to get a Restricted Data Token (RDT) to call restricted operations, is it a 'work in progress' ? 

Someone knows how to call its methods ?

**Comment by iamtaojie** [comment]
Have you solved the problem ? @alpapazzo

**Comment by alpapazzo** [comment]
Yes, you can use this class:
https://github.com/YucaApp/amazon-sp-api-php/commit/c2a66efac41e76a7a34644e7b68c68760044a15e
