### ISSUE TITLE
Create feed - The encrypted feed document contents were not uploaded to S3.

### ISSUE THREAD

**Issue by sunil11475-dev** [clousale/amazon-sp-api-php#97]
I am trying to make call to **CreateFeed** for **POST_ORDER_FULFILLMENT_DATA** but its not working - 

**_And I can't figure it out where to put $encryptedFeedData (order data file in script)._**

```
		$feedContentFilePath = '20-78-015737.txt';

		$config = $this->getconfig();
		$apiInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\FeedsApi($config);

		$contentType = 'text/xml; charset=UTF-8';

		$result = $apiInstance->createFeedDocument(new \ClouSale\AmazonSellingPartnerAPI\Models\Feeds\CreateFeedDocumentSpecification([
			'content_type' => $contentType,
		]));

		$feedDocumentId = $result['payload']['feed_document_id'];
		$url = $result['payload']['url'];
		$key = $result['payload']['encryption_details']['key'];
		$initializationVector  = $result['payload']['encryption_details']['initialization_vector'];

		$key = base64_decode($key, true);
		$initializationVector = base64_decode($initializationVector, true);
		$encryptedFeedData = openssl_encrypt(utf8_encode($feedContentFilePath), 'aes-256-cbc', $key, OPENSSL_RAW_DATA, $initializationVector);

		$data['feed_type'] = "POST_ORDER_FULFILLMENT_DATA";
		$data['marketplace_ids'] = ["A1F83G8C2ARO7P"];
		$data['input_feed_document_id'] = $feedDocumentId;

		$body = new \ClouSale\AmazonSellingPartnerAPI\Models\Feeds\CreateFeedSpecification($data);

		try {
			$result = $apiInstance->createFeed($body);
		} catch (Exception $e) {
			echo 'Exception when calling FeedsApi->createFeed: ', $e->getMessage(), PHP_EOL;
			$error = $e->getBody();
		}
```
Getting error - 

`Exception when calling FeedsApi->createFeed: [400] Client error: 'POST https://sellingpartnerapi-eu.amazon.com/feeds/2020-09-04/feeds' resulted in a '400 Bad Request' response: { "errors": [ { "code": "InvalidInput", "message": "The encrypted feed document contents were not uploaded to S3.", "details": "" } ] }`

**Comment by gokigoks** [comment]
Hi, were you able to answer this question? I am stuck on the same process, not sure  where to put the encrypted data. Any help is appreciated. Thanks

**Comment by sunil11475-dev** [comment]
@gokigoks check the below link, I used this code and its working for me --

https://github.com/clousale/amazon-sp-api-php/issues/61

**Comment by gokigoks** [comment]
@sunil11475-dev I'm stuck encrypting the Feed file. I use a tab-delimited flat file in my feed submission and I keep getting a 403 error: "SignatureDoesNotMatch". in your example though, you encoded the file name. Was wondering what I'm doing wrong and would appreciate any help from anyone.

**Comment by sunil11475-dev** [comment]
@gokigoks can you please provide you code so i can check.
